name: Setup
inputs:
  java-version:
    required: true
    default: 17
  cache-key:
    required: true
    default: "deps"

runs:
  using: composite
  steps:
    - name: Prepare JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: 1.11.1.1208
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.gitlibs
        key: v1-${{ hashFiles('deps.edn') }}-${{ inputs.cache-key }}
        restore-keys: |
          v1-${{ hashFiles('deps.edn') }}-
          v1-
