version: 2.1

########################################################################################################################
#                                                      EXECUTORS                                                       #
########################################################################################################################

executors:
  java-17:
    working_directory: /home/circleci/metabase/saml20-clj/
    docker:
      - image: circleci/clojure:openjdk-17-tools-deps-1.10.3.822-buster

  java-11:
    working_directory: /home/circleci/metabase/saml20-clj/
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.3.822-buster

  java-8:
    working_directory: /home/circleci/metabase/saml20-clj/
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps-1.10.3.822-buster


########################################################################################################################
#                                                       COMMANDS                                                       #
########################################################################################################################

commands:

  attach-workspace:
    steps:
      - attach_workspace:
          at: /home/circleci/

  restore-deps-cache:
    steps:
      - restore_cache:
          keys:
            - deps-{{ checksum "deps.edn" }}
            - deps-

jobs:

  checkout:
    executor: java-17
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - metabase/saml20-clj

  deps:
    executor: java-17
    steps:
      - attach-workspace
      - restore-deps-cache
      - run: clojure -P -X:dev:check:eastwood:test:namespace-checker:cloverage
      - run: clojure -P -X:jar
      - run: clojure -P -X:deploy
      - run: clojure -P -T:whitespace-linter
      - run: clojure -P -M:kondo
      - save_cache:
          key: deps-{{ checksum "deps.edn" }}
          paths:
            - /home/circleci/.m2
            - /home/circleci/.gitlibs

  clojure:
    parameters:
      e:
        type: executor
        java-17: java-17
      clojure-command:
        type: string
      after-steps:
        type: steps
        java-17: []
    executor: << parameters.e >>
    steps:
      - attach-workspace
      - restore-deps-cache
      - run:
          command: clojure << parameters.clojure-command >>
          no_output_timeout: 5m
      - steps: << parameters.after-steps >>

  reflection-warnings:
    executor: java-17
    steps:
      - attach-workspace
      - restore-deps-cache
      - run:
          command: ./check-for-reflection-warnings.sh
          no_output_timeout: 3m

  deploy:
    executor: java-17
    steps:
      - attach-workspace
      - restore-deps-cache
      - run: .circleci/release.sh


########################################################################################################################
#                                                      WORKFLOWS                                                       #
########################################################################################################################

workflows:
  version: 2
  build:
    jobs:
      - checkout

      - deps:
          requires:
            - checkout

      - clojure:
          name: tests-java-17
          requires:
            - deps
          clojure-command: -X:dev:test

      - clojure:
          name: tests-java-11
          requires:
            - deps
          e: java-11
          clojure-command: -X:dev:test

      - clojure:
          name: tests-java-8
          requires:
            - deps
          e: java-8
          clojure-command: -X:dev:test

      - clojure:
          name: eastwood
          requires:
            - deps
          clojure-command: -X:dev:eastwood

      - clojure:
          name: namespace-decls
          requires:
            - deps
          clojure-command: -X:dev:namespace-checker

      - clojure:
          name: check
          requires:
            - deps
          clojure-command: -M:check

      - clojure:
          name: cloverage
          requires:
            - deps
          clojure-command: -X:dev:cloverage
          after-steps:
            - run:
                name: Upload code coverage to codecov.io
                command: bash <(curl -s https://codecov.io/bash)

      - clojure:
          name: whitespace-linter
          requires:
            - deps
          clojure-command: -T:whitespace-linter

      - clojure:
          name: kondo
          requires:
            - deps
          clojure-command: -M:kondo

      - reflection-warnings:
          requires:
            - deps

      - deploy:
          requires:
            - check
            - eastwood
            - namespace-decls
            - tests-java-8
            - tests-java-11
            - tests-java-17
            - cloverage
            - reflection-warnings
            - whitespace-linter
            - kondo
          filters:
            branches:
              only: master
