name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'VERSION.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deployment
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
    - name: Prepare JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        cli: 1.11.1.1413
    - name: Build saml20
      run: clojure -T:build build
      env:
        GITHUB_SHA: ${{ env.GITHUB_SHA }}
    - name: Deploy saml20
      run: clojure -T:build deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
