name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Deployment
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          cache-key: "deploy"
      - name: Build JAR
        shell: bash
        run: >-
          set -x;
          clojure -X:jar :version "\"$(cat VERSION.txt)\""
      - name: Upload JAR to Clojars
        run: clojure -X:deploy :artifact '"target/saml20-clj.jar"'
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
